// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import { App } from 'aws-cdk-lib';
import { PipelineStack } from './pipeline_stack';
const app = new App();
new PipelineStack(app, 'PipelineStack');
app.synth();