// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import { EcsStack } from './ecs_stack';
import { Stage, StageProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
export class PipelineStage extends Stage {
  constructor(scope: Construct, id: string, props?: StageProps) {
    super(scope, id, props);
    new EcsStack(this, 'EcsStack');
  }
}