// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import { Stack, StackProps } from 'aws-cdk-lib';
import * as codecommit from 'aws-cdk-lib/aws-codecommit';
import { CodeBuildStep, CodePipeline, CodePipelineSource } from 'aws-cdk-lib/pipelines';
import { Construct } from 'constructs';
import { PipelineStage } from './pipeline_stage';
export class PipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const repo = new codecommit.Repository(this, 'cdkPipelinesRepo', {
      repositoryName: 'cdkPipelinesRepo'
    });
    const pipeline = new CodePipeline(this, 'Pipeline', {
      pipelineName: 'CdkPipeline',
      synth: new CodeBuildStep(
        'SynthStep', {
          input: CodePipelineSource.codeCommit(repo, 'master'),
          installCommands: [
            'npm install -g aws-cdk',
          ],
          commands: [
            'npm ci',
            'npm run build',
            'npx cdk synth',
          ],
        },
      ),
    });
    const deploy = new PipelineStage(this, 'Deploy');
    pipeline.addStage(deploy);
  }
}